# ===================================================================
# Spring Boot Core Configuration
# ===================================================================
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop

# ===================================================================
# log Configuration
# ===================================================================
logging:
  level:
    root: INFO
    org.springframework: INFO
    dev.kyudong.back: DEBUG
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG

# ===================================================================
# jwt Configuration
# ===================================================================
jwt:
  access-secret: SGVsbG9AI2UzV3JvbGQhQCN9RHxkc2prZC0oOTBNeVNlY3JldCEyMyRGREcjMw==
  refresh-secret: bXlyZWZyZXNoIXNlY2V0IUBrI2UleSoxOWNuZGRrYy4xMF9AIV8pYztseHZjeDhwYWp6Y3guV0FVKEBCZHNmZHM=
  access-expiration-time: 3600000
  refresh-expiration-time: 604800000

# ===================================================================
# file Configuration
# ===================================================================
media:
  base-path: /storage
  web-path: /media/
  host-path: D:\toy\uploads
  sub-paths:
    temp-dir: temp
    origin-dir: orgin
    process-dir: process
    user-dir: user
    post-dir: post
    chat-dir: chat

# ===================================================================
# datasource-proxy Configuration
# ===================================================================
decorator:
  datasource:
    enabled: true
    p6spy:
      enable-logging: true

# ===================================================================
# stomp Configuration
# ===================================================================
stomp:
  prefix: SW=