# ===================================================================
# Spring Boot Core Configuration
# ===================================================================
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop

# ===================================================================
# log Configuration
# ===================================================================
logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate: INFO
    dev.kyudong.back: DEBUG
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG
    net.ttddyy.dsproxy.listener.logging.SLF4JQueryLoggingListener: DEBUG
    net.ttddyy.dsproxy.listener.logging.SLF4JSlowQueryListener: WARN

# ===================================================================
# jwt Configuration
# ===================================================================
jwt:
  secret: SGVsbG9AI2UzV3JvbGQhQCN9RHxkc2prZC0oOTBNeVNlY3JldCEyMyRGREcjMw==
  expiration-time: 3600000

# ===================================================================
# file Configuration
# ===================================================================
file:
  upload-dir: /test/uploads
  public-web-path: /media/

# ===================================================================
# datasource-proxy Configuration
# ===================================================================
decorator:
  datasource:
    enabled: true
    datasource-proxy:
      json-format: true
      logging: slf4j
      multiline: true
      query:
        enable-logging: true
      slow-query:
        enable-logging: true
        log-level: INFO